### ISSUE TITLE
Handle TextCtrl with wx.TE_PROCESS_ENTER

### ISSUE THREAD

**Issue by z3ugma** [chriskiehl/re-wx#4]
Hi Chris - I'm attempting to define my own TextCtrl component that has `style=wx.TE_PROCESS_ENTER` and then Bind the `wx.EVT_TEXT_ENTER` event with a prop, something like `on_enter` for the TextCtrl. The Enter function would cause the gui to execute a function similar to how an `on_click` handler would. How would you recommend building such a component class?

**Comment by chriskiehl** [comment]
Hey @z3ugma, 

The handy escape hatch for when you need to do something WX specific is to use a `Ref` (checkout the docs [here](https://github.com/chriskiehl/re-wx/blob/main/docs/main-concepts.md#refs)). That'll give you a handle to the instance which you can use to `Bind` anything you need. 

Longer term, I plan to smooth over some of the warts in WX's various text ctrls. As is, needing to specifically pass a specific flag in order to hook into the `enter` key is _pretty wonky_ imo. 

If you pull the latest, I've patched the textctrl so that you can pass in `style`. I previously had these disabled while I figured out how to standardize how it's handled across widgets (WX does a kind of annoying thing where the semantic meaning of `style` sometimes changes between construction time versus instance time). 

At any rate: here's a small example that'll now work with v0.0.06:

```python
import wx

from rewx import create_element, wsx, render, Component, Ref
import rewx.components as c


class MyComponent(Component):
    def __init__(self, props):
        super().__init__(props)
        self.state = {'value': ''}
        self.input_ref = Ref()

    def component_did_mount(self):
        wx_ctrl = self.input_ref.instance
        wx_ctrl.Bind(wx.EVT_TEXT_ENTER, self.on_enter)

    def on_input(self, event):
        self.set_state({'value': event.EventObject.Value})

    def on_enter(self, event):
        wx.MessageDialog(None, "Enter pressed!").ShowModal()

    def render(self):
        return wsx(
            [c.Frame, {'title': 'My Cool Application', 'show': True},
             [c.Block, {'orient': wx.HORIZONTAL},
              [c.TextCtrl, {
                  'style': wx.TE_PROCESS_ENTER,
                  'value': self.state['value'],
                  'on_change': self.on_input,
                  'ref': self.input_ref,
              }]]]
        )



if __name__ == '__main__':
    app = wx.App()
    frame = render(create_element(MyComponent, {}), None)
    app.MainLoop()
```

**Comment by z3ugma** [comment]
Nice, the patch of `style` in 0.0.7 works exactly as I'd want with this example. Thank you!
